MainInterfaceAnimation:

<MainInterfaceAnimation>:


<My_ScreenManager>:
    ScreenManager:
        id: sm
        Screen:
            name: "first"
            Button:
                size_hint: 1, 0.5
                text: "First Screen"
                on_press: root.firstBtn(sm)
        Screen:
            name: "second"
            Button:
                size_hint: 1, 0.5
                text: "Second Screen"
                on_press: root.secondBtn(sm)


<Image_Viewer>:
    Image:
        source: "harpia-que-parece-pessoa-7.jpg"

<Canvas_tuts>:
    canvas:
        Color:
            rgba: .3, .4, .8, 1
        Line:
            circle: (200,200,100)
        Line:
            ellipse: (200, 400, 100, 200)
        Line:
            rectangle: (100, 400, 100, 20)
        Line:
            rounded_rectangle: (300,400,100,50,20)




<Game>:
    orientation: "vertical"
    ScrollView:
        Buttons:
            id: stacker
            size_hint: 1, None
            height: self.minimum_height
    BoxLayout:
        size_hint: 1, .2
        Button:
            text: "Create"
            on_press: root.create_btn()
            background_color: .3,.4,.5,1
            background_normal: ""
        Button:
            text: "remove"
            on_press: root.remove_btn()
            background_color: .6,.7,.8,1
            background_normal: ""

<Buttons>:
    padding: dp(10)
    spacing: dp(10)


<Variables>:
    #: set txt 40 # declaration variable in kivy language (set {variable} {value})
    anything: "Welcome To Root"
    Button:
        text: root.anything
        on_press: root.pressing(self)
    Label:
        text: root._text_
        font_size: txt

<LogicalInterface>:
    orientation: "vertical"
    Button:
        text: "Press Me"
        on_press: root.OnPressing(label, input)
        on_release: root.OnReleasing(label, input)
    Label:
        id: label
        text: "Hello World!"
    TextInput:
        id: input
        multiline: False
        text: "Please Enter Your Equation"


<Page_Layout>:
    Page_1:
    Page_2:
    Page_3:


<Relative_Practice>: #FloatLayout
    RelativeLayout:
        size_hint: .40, .40 #percent
        pos: 100, 100
        Button:
            text: "Child"
            size_hint: .40, .40
            pos_hint: {"x": 0, "bottom": 1}




<Scroller_Func@ScrollView>
    #properties
    bar_margin: 5
    bar_color: 0.3, 0.4, 0.5, 1
    bar_width: 10
    bar_inactive_color: 1,0,0,1
    StackInterface:
        size_hint: 1, None
        height: self.minimum_height


#root(class behaviors)
#stackInterface:

#rule(class properties)
<StackInterface>: # Now, is a StackLayout
    padding: [40, 0, 40, 40]
