#rule
<Interface>:
#root
Interface:
    Button:
        text: "Hello World!"
        pos: 300, 300 #position button
        size: 200, 100 #size button
        color: 'black'
        background_color: 'red'
    Button:
        text: "Hello World!"
        pos: 100, 300 #position button
        size: 200, 100 #size button
        color: 'black'
        background_color: 'greenyellow'
    Button:
        text: "Hello World!"
        pos: 500, 300 #position button
        size: 200, 100 #size button
        color: 'black'
        background_color: 'blue'